[nitpick]
minimum_version = "0.21.0"

[nitpick.styles]
include = [ "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/flake8.toml", "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/isort.toml", "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/darglint.toml",]

["setup.cfg".isort]
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true

["setup.cfg".flake8]
strictness = "long"
